### PR TITLE
Display all seasons

### LINKED ISSUE #315: Opening the create season page gives 500 in backend.
Steps to reproduce: 
fresh db
open network tab
click create season

### PR DESCRIPTION
**Pull request by Paalar**
- Add a page to see app application seasons
- Sorted by highest id
- Resolves #315, #314

### CODE REVIEW

File: frontend/src/components/ApplicationSeason/reducer.tsx [hunk 1]
```diff
@@ -22,6 +23,7 @@ export const initialState = {
     applicationPeriodEnd: minDate,
     applicationPeriodStart: minDate,
     end: minDate,
+    id: -1,
```
Comment (PeterRydberg) [inline frontend/src/components/ApplicationSeason/reducer.tsx]: Is this meant to initialize the ID to -1 if undefined? Can't you just make the currentSeason nullable?

File: frontend/src/components/ViewApplicationSeasons/SeasonLink.tsx [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+      to={{ pathname: panelProps.href, room: { ...season } }}
+      className="lenkepanel lenkepanel--border"
+    >
+      {panelProps.children}
+    </NavLink>);
+  return (
+    <LenkepanelBase
+      key={season.id}
+      linkCreator={link}
+      href={`${ROUTE_TO}${season.id}`}
```
Comment (PeterRydberg) [inline frontend/src/components/ViewApplicationSeasons/SeasonLink.tsx]: This will 404, no route to update-season

File: frontend/src/components/ApplicationSeason/reducer.tsx (hunk 1 above)
Comment (Paalar) [reply frontend/src/components/ApplicationSeason/reducer.tsx]: I'm changing it to 0, but the point is when the id is 0 it will not have inherited or fetched a season, meaning it is supposed to create a new one. Changing the layout and functionality

Comment (FluidSense) [reply frontend/src/components/ApplicationSeason/reducer.tsx]: Would it not make more sense to make currentSeason nullable if it doesn't exist, since it's a better reflection of what it actually is as @PeterRydberg suggests? And then handle undefined the same way as you to with ID 0 or -1 right name?

File: frontend/src/components/ViewApplicationSeasons/SeasonLink.tsx (hunk 2 above)
Comment (FluidSense) [reply frontend/src/components/ViewApplicationSeasons/SeasonLink.tsx]: @Paalar Why did you resolve this? Please add a comment to why.

Comment (Paalar) [reply frontend/src/components/ViewApplicationSeasons/SeasonLink.tsx]: Forgot to mention. It is resolved in #255

File: frontend/src/components/ApplicationSeason/reducer.tsx (hunk 1 above)
Comment (Paalar) [reply frontend/src/components/ApplicationSeason/reducer.tsx]: I forgot which PR this was, my bad. This is resolved in #255

**Comment by PeterRydberg** [comment]
Go ahead and merge in master to get the fixes from #255, then I think we're good!
